// Generated by IcedCoffeeScript 108.0.11
(function() {
  var ast, k, v;

  ast = window.ast4gen;

  for (k in ast) {
    v = ast[k];
    this[k] = v;
  }

  this.Fn_decl_multiret = (function() {
    Fn_decl_multiret.prototype.is_closure = false;

    Fn_decl_multiret.prototype.name = '';

    Fn_decl_multiret.prototype.type_i = null;

    Fn_decl_multiret.prototype.type_o = null;

    Fn_decl_multiret.prototype.arg_name_list = [];

    Fn_decl_multiret.prototype.scope = null;

    Fn_decl_multiret.prototype.line = 0;

    Fn_decl_multiret.prototype.pos = 0;

    function Fn_decl_multiret() {
      this.arg_name_list = [];
    }

    return Fn_decl_multiret;

  })();

  this.Ret_multi = (function() {
    Ret_multi.prototype.t_list = [];

    function Ret_multi() {
      this.t_list = [];
    }

    return Ret_multi;

  })();

  this.For_3pos = (function() {
    For_3pos.prototype.init = null;

    For_3pos.prototype.cond = null;

    For_3pos.prototype.incr = null;

    For_3pos.prototype.scope = null;

    function For_3pos() {
      this.scope = new ast.Scope;
    }

    return For_3pos;

  })();

}).call(window.mod_ast = {})
